# Generated by Django 3.1.7 on 2021-03-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mensagem', models.CharField(blank=True, max_length=50, null=True)),
                ('ddd', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('operadora', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_envio', models.CharField(blank=True, max_length=20, null=True)),
                ('mensagem', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
    ]
