# Generated by Django 3.1.7 on 2021-03-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArquivoEntrada',
            new_name='Campanha',
        ),
    ]
