# Generated by Django 3.1.7 on 2021-03-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_auto_20210320_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_broker', models.IntegerField(blank=True, null=True)),
                ('operadora', models.CharField(blank=True, choices=[('OI', 'OI'), ('CLARO', 'CLARO'), ('VIVO', 'VICO'), ('TIM', 'TIM'), ('NEXTEL', 'NEXTEL')], max_length=15, null=True)),
            ],
        ),
    ]
