# Generated by Django 3.1.7 on 2021-03-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mensagem', models.CharField(blank=True, max_length=50, null=True)),
                ('ddd', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('operadora', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_envio', models.CharField(blank=True, max_length=20, null=True)),
                ('mensagem', models.CharField(blank=True, max_length=140, null=True)),
                ('status', models.CharField(blank=True, choices=[('I', 'Inválido'), ('B', 'Blacklist'), ('V', 'Valido')], max_length=3, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Campanha',
        ),
    ]
