# Generated by Django 3.1.7 on 2021-03-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0009_auto_20210320_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mensagem', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('id_broker', models.IntegerField(blank=True, null=True)),
                ('operadora', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
