# Generated by Django 3.1.7 on 2021-03-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0010_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='status',
            field=models.CharField(blank=True, choices=[('Blacklist', 'Blacklist'), ('Inválido', 'Inválido'), ('Valido', 'Valido'), ('Não Permitido', 'Não Permitido')], max_length=30, null=True),
        ),
    ]
