version: '3'

services:
  mysql:
    image: mysql
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password